# Generated by Django 5.2.5 on 2026-10-02 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(db_index=True, max_length=60, verbose_name='Type de notification')),
                ('canal', models.CharField(max_length=20, verbose_name='Canal')),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé'), ('ignore', 'Ignoré'), ('echec', 'Échec')], max_length=10, verbose_name='Statut')),
                ('detail', models.CharField(blank=True, max_length=500, verbose_name='Détail')),
                ('cle_unique', models.CharField(blank=True, db_index=True, max_length=200, verbose_name="Clé d'idempotence")),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_envoyees', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Journal de notification',
                'verbose_name_plural': 'Journal des notifications',
                'ordering': ['-date_envoi'],
                'indexes': [models.Index(fields=['type_notification', '-date_envoi'], name='Notificatio_type_no_750fd7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cle_unique', ''), _negated=True), fields=('canal', 'cle_unique'), name='notification_unique_par_canal_et_cle')],
            },
        ),
    ]
