# Generated by Django 6.0.5 on 2026-05-24 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestataire',
            name='metier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestataires', to='main.prestation', verbose_name='Métier'),
        ),
        migrations.AlterField(
            model_name='prestataire',
            name='quartier',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Quartier/Zone d'intervention"),
        ),
        migrations.AlterField(
            model_name='prestataire',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='prestataire',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ville', verbose_name='Ville'),
        ),
    ]
