# Generated by Django 6.0.5 on 2026-05-25 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_prestataire_metier_alter_prestataire_quartier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prestataires/realisations/', verbose_name='Image')),
                ('titre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre de la réalisation')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realisations', to=settings.AUTH_USER_MODEL, verbose_name='Prestataire')),
            ],
            options={
                'verbose_name': 'Réalisation',
                'verbose_name_plural': 'Réalisations',
            },
        ),
    ]
