# Generated by Django 6.0.5 on 2026-05-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_evaluation_client_alter_evaluation_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='code_verification',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Code de vérification'),
        ),
    ]
