# Generated by Django 6.0.5 on 2026-05-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_prestataire_code_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='call_clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='Clics appel'),
        ),
        migrations.AddField(
            model_name='prestataire',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AddField(
            model_name='prestataire',
            name='profile_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Vues du profil'),
        ),
        migrations.AddField(
            model_name='prestataire',
            name='role',
            field=models.CharField(choices=[('prestataire', 'Prestataire'), ('client', 'Client')], default='prestataire', max_length=20, verbose_name='Rôle'),
        ),
    ]
