# Generated by Django 6.0.3 on 2026-05-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_prestataire_call_clicks_prestataire_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='contact_clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='Clics contact'),
        ),
    ]
