# Generated by Django 5.2.5 on 2026-10-02 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_notification_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realisation',
            options={'ordering': ['-date_ajout'], 'verbose_name': 'Réalisation', 'verbose_name_plural': 'Réalisations'},
        ),
        migrations.AddField(
            model_name='realisation',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realisations', to='main.categorieprestation', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='contenu',
            field=models.TextField(blank=True, default='', verbose_name='Texte de la publication'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='lien',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Lien externe'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='modifie_le',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifiée le'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='prestataires/videos/', verbose_name='Vidéo'),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prestataires/realisations/', verbose_name='Image principale'),
        ),
        migrations.CreateModel(
            name='RealisationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prestataires/realisations/', verbose_name='Image')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('realisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.realisation', verbose_name='Réalisation')),
            ],
            options={
                'verbose_name': 'Image de réalisation',
                'verbose_name_plural': 'Images de réalisation',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
